language: c

sudo: false

services:
  - mysql

addons:
  postgresql: "10"
  apt:
    packages:
      - libgmp-dev
      - postgresql-10
      - postgresql-client-10
      - postgresql-server-dev-all

env:
  global:
    - PGPORT=5432
  matrix:
    - GHCVER=8.2
    - GHCVER=8.4
    - GHCVER=8.6

install:
  - export STACK_YAML=stack-$GHCVER.yaml
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version
  - psql -c "CREATE USER esqutest WITH PASSWORD 'esqutest';" -U postgres
  - createdb -O esqutest esqutest
  - mysql -e 'CREATE DATABASE esqutest;'

script:
  - stack setup
  - stack update
  - stack build
  - stack test
  - cd test/expected-compile-failures/
  - bash test.sh

cache:
  directories:
  - $HOME/.stack
